### PR TITLE
Bundler niceties

### PR DESCRIPTION
**Pull request by michaelherold**
Adds some basic bundler helper scripts that make it really easy to get up and running with development.

* `bin/console` starts a REPL with `reductio` already required, along with anything else you specify there.
* `bin/setup` runs `bundle install` (and in some cases other stuff) in a consistent setup interface.

Also adds the gemspec to the Gemfile. This makes sure that Bundler requires `reductio` and its (currently non-existant) dependencies when you call `Bundler.setup`. This helps with the `bin/console` command by auto-requiring `reductio`.

### CODE REVIEW

**Comment by lambdatastic** [comment]
It's failing because `Gemfile.lock` didn't get updated, but it's removed in the current master. If you merge it in, I think this will pass CI.

**Comment by michaelherold** [comment]
I rebased on top of master so it should be good to go now.

Great job with your RubyConf talk! 👍

**Comment by lambdatastic** [comment]
Thanks!

**Review by lambdatastic — APPROVED** [review]
👍

**Pull request merged**
